### ISSUE TITLE
Dataset cannot be unzip

### ISSUE THREAD

**Issue by Boltzmachine** [LengSicong/Tell2Design#1]
I download the dataset zip file from the link you provided. But when I unzip it
```
file #2:  bad zipfile offset (local header sig):  212
...
```
It seems that the file you uploaded is broken?

**Comment by LengSicong** [comment]
Sorry for the inconvenience. The link has been updated in the readme file. (https://drive.google.com/file/d/1ZkoDAE72qy-62nO_kul7YSVT0v5Xz87R/view?usp=sharing)
