### ISSUE TITLE
Input dataset label bounding box doesn't match with the input labelled images

### ISSUE THREAD

**Issue by akssieg** [LengSicong/Tell2Design#11]
I downloaded the dataset from the link provided in the README. Next, I imported the floorplan_eval.json file into my Jupyter Notebook and visualized the first row of the dataset. The image ID of the first row is '3326'. The image is shown below:
<img width="134" alt="image" src="https://github.com/LengSicong/Tell2Design/assets/32209750/d262038e-4b45-404f-8ea6-34656c60e2bc">
When I tried to visualize the bounding boxes, I got the following image:
<img width="367" alt="image" src="https://github.com/LengSicong/Tell2Design/assets/32209750/3052101a-0da9-47f7-9171-6cd837e8d49f">
 I think the data in the dataset doesn't correspond to the image label. Please correct me if I am wrong. 
@LengSicong @yangzhou12 @shuiba0

**Comment by LengSicong** [comment]
Please check the x,y mapping of the bounding boxes
