### ISSUE TITLE
floorplan_train.json 

### ISSUE THREAD

**Issue by chenyonx** [LengSicong/Tell2Design#12]
No such file or directory: 'data/floorplan/floorplan_train.json',the https://drive.usercontent.google.com/download?id=1ZkoDAE72qy-62nO_kul7YSVT0v5Xz87R&export=download&authuser=0 hasnot the json

**Comment by Gloria0925** [comment]
same question

**Comment by LengSicong** [comment]
Please refer to this [issue](https://github.com/LengSicong/Tell2Design/issues/8).
