### ISSUE TITLE
When I train t5-base, how do I fix this?

### ISSUE THREAD

**Issue by THU-Kingmin** [LengSicong/Tell2Design#3]
When I train t5-base, how do I fix this?
“Token indices sequence length is longer than the specified maximum sequence length for this model (517 > 512). Running this sequence through the model will result in indexing errors
Max sequence length is 512 but the longest input sequence is 519 long
Killed”

**Comment by THU-Kingmin** [comment]
I found out that it was an error in this piece of code that was causing KILLED.
# output_index = [self.output_format.format_output_index(example) for example in self.examples]
# output_tok = self.batch_encode_output_(output_index, max_output_length)

output_tok = self.tokenizer.batch_encode_plus(
    output_sentences,
    max_length=max_output_length,
    return_tensors='pt',
    padding='max_length',
    truncation=True,
)

**Comment by LengSicong** [comment]
It should be fine once you set the "truncation" to True. 
If not, you can try to truncate the sequence manually.
