### ISSUE TITLE
Release model checkpoints (floorplan-t5-base)

### ISSUE THREAD

**Issue by THU-Kingmin** [LengSicong/Tell2Design#5]
Can you release the model checkpoints? For example, floorplan-t5-base, surely it would be best to be able to release all the checkpoints for the models compared in the article. Baidu NetDisk or Google NetDisk is fine.

**Comment by LengSicong** [comment]
Please refer to the link of google drive, which contains the checkpoint for the final model. https://drive.google.com/file/d/1k0NJiy7pW5icSsMjRxI1Z2gso-zWKC50/view?usp=sharing
