### ISSUE TITLE
A question about boundary information

### ISSUE THREAD

**Issue by PaulLiuYZ** [LengSicong/Tell2Design#6]
Hello sicong！
Thanks for your great job tell2design and congratulations!
However, i have some questions, i wonder how is the boundary information provided with only the text? And i notice that in the code, there is "data_args.boundary_in_where" which controls the place of boundary information used, what are the differences of using them in the encoder or decoder?
I will appreciate it a lot if you can answer my questions!

**Comment by LengSicong** [comment]
<img width="580" alt="image" src="https://github.com/LengSicong/Tell2Design/assets/55685981/b78a3531-39d0-49fb-9951-d766a0aa56b4">
Please refer to section 4.2 of our paper for a detailed description of how to represent the boundary using text-only tokens.

**Comment by LengSicong** [comment]
The "data_args.boundary_in_where" is the early experimental exploration. If the boundary is used in the encoder, it would be considered given information. However, if it is used in the decoder as part of the output sequence, it may be a constraint and control the generation of the later actual floorplan sequence.

**Comment by PaulLiuYZ** [comment]
Thanks for your reply!
In the paper, the boundary is represented by the bounding box, however, from the original text, the bounding box is not explictly expressed, so the bounding box is also got by the language model?
![image](https://github.com/LengSicong/Tell2Design/assets/66100217/aa8d9188-ca54-4062-a166-ec09fb945c4c)
For "data_args.boundary_in_where", so boundary is now also part of the output which guided the following sequence?

**Comment by LengSicong** [comment]
In the figure or demonstration from the paper, we ignore the boundary sequence for simplicity. However, the boundary is parsed into a sequence of tokens and concatenated with the natural language descriptions as input to the encoder.

**Comment by PaulLiuYZ** [comment]
Thanks for your reply!
