### ISSUE TITLE
human annotators

### ISSUE THREAD

**Issue by THU-Kingmin** [LengSicong/Tell2Design#7]
Hello! Can you tell me which image is used in Figure 4 of the paper and what is the image ID? Can you give a download link for the image of human annotators based on the language instructions?

**Comment by LengSicong** [comment]
Sorry that we cannot identify the image ID now. You can download the image and text of the human annotation here.
[annotated_imgs.zip](https://github.com/LengSicong/Tell2Design/files/13065728/annotated_imgs.zip)
[annotated_text.zip](https://github.com/LengSicong/Tell2Design/files/13065730/annotated_text.zip)
