### ISSUE TITLE
How to get floorplan_test.json

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [LengSicong/Tell2Design#8]
Hi 
Thanks and congrats on this great repo!

When i run :
`python run.py floorplan
`
I get `FileNotFoundError: [Errno 2] No such file or directory: 'data/floorplan/floorplan_test.json'`

Where can I get teh floorplan_test.json?

Thanks in advance

**Comment by LengSicong** [comment]
Hi, thanks for your interest!

As mentioned in the readme file, you can download all data files from [here](https://drive.google.com/file/d/1ZkoDAE72qy-62nO_kul7YSVT0v5Xz87R/view?usp=sharing).

**Comment by reddy92rosh** [comment]
I downoaded the dataset from the link shared, yet I cannot find the floorplan_train.json file. Could you please direct me towards it?

**Comment by chenyonx** [comment]
yes,i'm also meet the same trouble, no train.json, have you solve it?

**Comment by LengSicong** [comment]
The json file for each stage is stored under each stage's "T5" subfolder, e.g., Tell2Design Data/Separated Data/1st_finetune_data/T5/floorplan_train_wo_human.json

**Comment by Gloria0925** [comment]
where should I save the dataset files? if my project root is located in **E:\8-Floorplan\Tell2Design-main**, I extract all files from your dataset and put them into my root folder, right? 
![111](https://github.com/user-attachments/assets/5f04dfcf-4eff-4ae6-bb6f-c7c83d992e7b)
![Pin_08-18](https://github.com/user-attachments/assets/5e40dfc9-d240-4b31-a551-7a834f8b81e3)
for this question, I need just create a **data/floorplan/floorplan_test.json** as subfolder and files? thanks for your kind reply

**Comment by LengSicong** [comment]
You can check the code for data loading paths. Thanks.

**Comment by yusuke0324** [comment]
I have the same error message, did any one solve this issue? I'm wondering Which json files I need to put to data/floorplan/

@LengSicong Can you tell us which code we should look at?
