### ISSUE TITLE
Inconsistency of the number in the dataset

### ISSUE THREAD

**Issue by Ydongd** [LengSicong/Tell2Design#9]
It seems that the number of the human-annotated dataset is inconsistent with the description in the paper.

The number of the human-annotated set is 5,051 in the paper, which is 4,003 in the released data. This inconsistency leads to overlap in the 2nd fine-tuned data and the evaluation data.

Is there something missed?

Looking forward to your response!

**Comment by kausainshah** [comment]
Hi @Ydongd,
I am also facing same issue. Any progress or update on this?

**Comment by LengSicong** [comment]
There are data samples where one floorplan corresponds to multiple language description annotations, which leads to inconsistency.
